### ISSUE TITLE
Give staff/admin the ability to see more info about the person of the recording

### ISSUE THREAD

**Issue by kmahelona** [TeHikuMedia/corpora#12]
As we're curating the corpus here (te reo Māori) the curators (staff/admin) need to be able to more fully understand who is speaking. While this may raise privacy concerns in a western sense, the amount of language lost suffered by most indigenous languages means that our language is in a mixed state. There is "academic" Māori learned from schools and universities which doesn't sound like native Māori learned through generational transmission. We need to be able to classify both types of these Māori as both are important today. Furthermore, the Māori community is quite small and given the kaitiakitanga licensing Te Reo Irirangi o Te Hiku o Te Ika use for this corpus, privacy in a Māori sense implies different things. When you enter a marae as a manuhiri, you disclose who your ancestors are, where you come from, and why you've come to the marae. In this respect, this information is important for our curators in collecting te reo Māori corpus. While traditionally this is done face to face, that doesn't scale well in order to collect the amount of data needed to train machines to understand te reo. Sharing more information about people contributing corpus with curators therefore helps apply our ways of doing things digitally.

**Comment by kmahelona** [comment]
First step is to add the following additional information to the listen view

- Person name & email (with link to send email)
- Person info
    - age, gender
   - language level
   - dialect / where did they learn Māori (need to add this to the models)
- Ability to delete recordings
    - Do we need to then provide them with a message as to why it was deleted?

**Comment by douglasbagnall** [comment]
Other projects collect age, gender, dialect.

Age is sometimes asked with just three options (child, adult, elderly adult), because your voice doesn't change all that much in the middle years.

Regarding deleting: would it sometimes be better to just ignore recordings without deleting them? They would just not go into training.

**Comment by kmahelona** [comment]
Deleting - yes, but you do get some really bad ones e.g. no sound at all or said the wrong thing. We could transcribe the recording anyway and use that. I'd delete the ones with no sound, but I think we should keep the ones that are incorrect as maybe we could use that for training purposes.

I think I'll migrate the Age field to a multiple choice of age range (much like Mozilla Voice).

**Comment by kmahelona** [comment]
Implemented.
