### ISSUE TITLE
Setup default local data for development

### ISSUE THREAD

**Issue by cr0mbly** [TeHikuMedia/corpora#212]
### Summary

On Kuaka/Kaituhi we have approach setup for automated generation of local data to help developers get the ball rolling with feature implementations/bug-fixes so they have something to work with. We should add something similar here so out local environment is pre-setup for development. 

It might be helpful for @edwardabraham or someone familiar with Corpora/KoreroMaori prod data to note down what they would like to see here to aid them in their work.

An example of how it works can be seen [here](https://github.com/TeHikuMedia/kuaka/tree/tumu/kuaka/demo) for kuaka it's very basic but provides the basic outline of data we need to develop on there, and is run through a `manage.py seed` Django managment command.

**Comment by edwardabraham** [comment]
I am having a little go at this, as it is good to have test data to write data migrations against. Will report back if I make progress!
