### ISSUE TITLE
[Pronunciation] Add spaces as a character to review.

### ISSUE THREAD

**Issue by kmahelona** [TeHikuMedia/corpora#232]
- [ ] @hlm628 to confirm the rules for this with and post them here the assign to @kmahelona

**Comment by kmahelona** [comment]
How do we migrate existing recordings that have been labeled for this.

**Comment by hlm628** [comment]
> How do we migrate existing recordings that have been labeled for this.

1. Look for existing reviews in which the phrase contains the pattern "*vowel* *vowel*" (e.g. 'a a'). 
2. If any of these have had either of the vowels labelled incorrect, have them re-reviewed with the space included.

The number of re-reviews should be quite small.

>     * [ ]  @hlm628 to confirm the rules for this with and post them here the assign to @kmahelona

I will write this up, and run past the data team.

**Comment by kmahelona** [comment]
@hlm628 I've got this going now like,
```json
{"characters": [
  {"W": false}, {"h": false}, {"a": false}, {"k": false}, {"a": false}, {"p": false}, {"ā": false}, {"h": false}, {"o": false}, {"n": false}, {"g": false}, {"i": false}, {"a": false}, {" ": true}, {"n": false}, {"g": false}, {"ā": false}, {" ": true}, {"p": false}, {"ā": false}, {"n": false}, {"u": false}, {"i": false}, {" ": false}, {"o": false}, {" ": false}, {"M": false}, {"u": false}, {"r": false}, {"i": false}, {"w": false}, {"h": false}, {"e": false}, {"n": false}, {"u": false}, {"a": false}],
"ratingSlider": null, "ratingComputed": 0.9444444444444444}
```

<img width="904" alt="Screen Shot 2021-04-21 at 1 59 50 PM" src="https://user-images.githubusercontent.com/5294466/115486000-df08ca00-a2a9-11eb-8003-f9d6b179fe9e.png">
* doesn't related to json above

Essentially I'm adding in the spaces. I believe punctuation was already included. I haven't migrated any old data, and maybe, as you suggest, we just review it again rather than try to migrate these.
