### ISSUE TITLE
Some recordings and sentences don't match!

### ISSUE THREAD

**Issue by kmahelona** [TeHikuMedia/corpora#25]
> There is one speaker whose audio doesn't match the text at all (it seems to have been shuffled)

This is a significant issue that appeared to be isolated to a single individual but now appears to be happening to two users.

**Comment by kmahelona** [comment]
I'm going to add device/browser information to recordings that way we may be able to isolate this to particular devices if that's the case.

**Comment by edwardabraham** [comment]
Great, It was the recordings by TeAkaManea that had the issue. It seems that they could be recovered - i.e., the audio could be associated with the correct prompts and the database patched.  The recordings by Whakaangi had a range of issues, including silence, and they sometimes also had the wrong text being associated with the recording.

**Comment by kmahelona** [comment]
Yup, we can certainly still use the recordings and can manually fix them through the django admin interface.

**Comment by kmahelona** [comment]
I've cleaned up the two instances where this was an issue. AFAIK there are only two cases of this happening. I'm hoping that recent major update prevents this from happening again.

**Comment by kmahelona** [comment]
Closing this as this bug no longer appears to occur.
