### ISSUE TITLE
Rōpū Attribute

### ISSUE THREAD

**Issue by kmahelona** [TeHikuMedia/corpora#31]
Allow people to associate with one or more groups. This will help in the competition and leaderboard. Ideally this is an auto suggest tag. We'll just let them write whatever. If they want their groups to win they'll have to ensure they use the proper name.

**Comment by kmahelona** [comment]
Hey @gregplaysguitar this is working great. 

Currently he site is set up so people don't have to create accounts and login and they can just contribute corpus and even provide details of their profile if they choose.

I noticed the Group field requires you to be logged in - which makes sense because we obviously don't want someone just adding a tone of group strings without being authenticated. I'm wondering how best to let the user know that they'll need to create an account or log in if they want to be a part of a group. Perhaps the better thing to do is rethink the design of the profile page, and we may move group out into an area that related to the leader board stuff. 

Perhaps a quick fix is a custom error that says "can't find your group, login or signup to create a new one."

**Comment by gregplaysguitar** [comment]
Ok, I've added help text for non-logged-in users, see f1f4f7d462022c638c22278b83d9d7feac17e14e
