### ISSUE TITLE
Text file parser to create sentences

### ISSUE THREAD

**Issue by kmahelona** [TeHikuMedia/corpora#33]
Given a text file (of a particular language), we should extract the sentences and add them to the database.

- We'll need to decide whether we exclude certain text such as headings
- We'll want a way to link the sentences back to their source file and location
- If sentences are edited, we may want to compile a version of the source text that has the edited sentences. This can then be used in the language model.
  - This may also require keeping a copy of the original sentence in the Sentence model. In fact it's  probably a good idea to add "original_text" field to the Sentence model anyway!
- If a doc is flagged as a particular language, we should ignore any sentences that don't represent that language.

**Comment by kmahelona** [comment]
@douglasbagnall you have a way to strip english out right? We have a body of text Peter really wants to use but has heaps of english as well.

**Comment by gregplaysguitar** [comment]
> If sentences are edited, we may want to compile a version of the source text that has the edited sentences. This can then be used in the language model.

What do you mean, "used in the language model"? I couldn't see a model of that name?

**Comment by kmahelona** [comment]
Sorry, "language model" isn't a Django model. It's the actual Māori language model we'll create from corpus.

**Comment by edwardabraham** [comment]
Just a comment here. The language model will be using paragraphs (chunks of text bigger than a sentence, as context may be preserved across sentence boundaries).  We will extract paragraphs from the source text and classify each one by how many Maori words we think it has (relative to the total words). We will use this to identify which paragraphs are largely in Te Reo, and will look to load paragraphs that are largely Te Reo, and that are more than a few words long. Ideally we will load the source and the paragraphs into Te Reo.

It would be great to be able to edit the paragraphs. In general, for any editing, I prefer making a linked list with the original source and then edited versions linking back to the one they came from. The original is then the one at the base of the list, and the current is the one at the head. On each edit record the datetime and who made the edit. This gives full historicisation (I think there are Django libaries that provide this out of the box). 

Sentences should be pulled out manually to be used as speech prompts (not all sentences are good for readers, and we don't need hundreds of thousands of sentences). They can then be edited independently of their source. I don't think that compiling corrected sentences back into text is necessary. The text corpus will be much larger than the needs of Korero Maori.

**Comment by kmahelona** [comment]
As we discussed at our hui, we wont try and "recreate" a text from the sentences model. Right now we just have a simple way of getting more sentences into the app for people to read. As work is done on our other projects, [nga-kupu](https://github.com/TeHikuMedia/nga-kupu) & [nga-tautohetohe](https://github.com/TeHikuMedia/nga-tautohetohe),  we'll hopefully be able to build in more capability to parse original bodies of texts into the formats necessary for the models.

I also agree that some sort of streamline, web based, editing functionality could be useful. I can see the same tool being used to help correct the machines. The same tool could also be used in the [django-colloquial](https://github.com/TeHikuMedia/django-colloquial) project. Surely someone somewhere has started some web based tool that's kinda what we need.

**Comment by kmahelona** [comment]
Current implementation (https://github.com/TeHikuMedia/corpora/commit/66ff0ae832a4cd5eb6a22a4c9e2b2610a900e399) is sufficient for our purposes. I'll create a new enhancement later once we have an idea of the types of text files we'll be uploading (e.g. a "clean" .txt versus a word doc) and the levels of parsing we'll need to do.
