### ISSUE TITLE
Add "datetime" to recording.

### ISSUE THREAD

**Issue by kmahelona** [TeHikuMedia/corpora#35]
This can help us when trying to understand bugs. But also helps us understand how people are recording (e.g. all at one, a few each day, etc.)

**Comment by kmahelona** [comment]
Just wondering if this is necessary since the file name essentially has datetime.

**Comment by gregplaysguitar** [comment]
much easier to filter/order on a datetime field?

**Comment by edwardabraham** [comment]
:+1: I have had issues with keeping information in filenames in the past.

**Comment by kmahelona** [comment]
Cool. Add it. 

On 12/12/2017, at 12:32, Greg Brown <notifications@github.com> wrote:

much easier to filter/order on a datetime field?
