### ISSUE TITLE
Envouraging wide ranging participation

### ISSUE THREAD

**Issue by edwardabraham** [TeHikuMedia/corpora#38]
A problem with leaderboards is that they can be demotivating for people who feel that they are far off the pace (i.e., one rōpu might dominate early on, and so the others don't bother joining in). We want diverse participation, rather than This is why systems like Stackoverflow use badges and so to create feedback for beginners.

A couple of approaches could be used to tackle this: one would to have a short time leaderboard (say weekly), which reflects effort made in that week (rather than an overall leaderboard). This could then be rewarded with a weekly draw.  This has the advantage of creating a bit of excitement as things go along, rather than waiting for the end of the project for the big prize.

Another technique used in every town hall fund raising is to issue spot prizes  (to anyone participating), so that people have a chance of getting reward, even though they aren't the winners.

**Comment by kmahelona** [comment]
Closing this as competition dynamics is currently something that we manage outside of the app.
