### ISSUE TITLE
Autocomplete search to ignore macrons

### ISSUE THREAD

**Issue by gregplaysguitar** [TeHikuMedia/corpora#40]
I noticed this:

https://github.com/TeHikuMedia/corpora/blob/master/corpora/people/views/autocomplete.py#L12

Postgres has an unaccent extension which we could use for this. So something like 

    select name from people_tribe where unaccent(name) like unaccent('%QUERY%');

Could also use a fulltext index, if you want it to work better

@kmahelona thoughts on this? I'm happy to go ahead if you think this is a good idea

**Comment by kmahelona** [comment]
If this only applies to queries where we have to explicitly ask to use unaccent (eg doesn’t affect current Django queries) then I’m happy with that. You’ll have to update the deploy code to add the extension.

Does that also mean you’ll need to do a raw Postgres DB call? This seems much simpler than installing something like solr.

On 12/12/2017, at 15:00, Greg Brown <notifications@github.com> wrote:

(note, we'd need to enable the extension -

CREATE EXTENSION unaccent;
)

**Comment by gregplaysguitar** [comment]
Probably a raw db query, but might be able to to it with the queryset. Raw is fine though.

**Comment by gregplaysguitar** [comment]
I've updated the deploy code, you should be able to run it with the tag postgres-ext before deploying this.
