### ISSUE TITLE
Dialect

### ISSUE THREAD

**Issue by edwardabraham** [TeHikuMedia/corpora#41]
At the moment the dialects are listed as:
- Kaitahu
- Muriwhenua
- Taranaki
- Tuhoe

I am concerned that that many people won't fit into any of these boxes, for example Whanganui pronunciation isn't covered. Ideally, this would be a list that everyone could place themselves in. (this could be covered by the default being something apart from '---' ).

You ask which iwi people affiliate with (which is a multi select). One option would be to ask people which iwi their speaking voice is associated with (i.e., where they learnt their reo)?

I am sorry I don't have a specific recommendation here!

**Comment by kmahelona** [comment]
This is properly implemented here: https://github.com/TeHikuMedia/corpora/commit/b209633bdc85c0deefca7559232e2933db57f2bf

Peter-Lucas consulted with another language expert, and we've settled with:

    ('mi', (
            ('tokerau', _('Te Tai Tokerau')),
            ('tainui', _('Tainui')),
            ('rawhiti', _('Te Tai Rawhiti')),
            ('hauauru', _('Te Tai Hauauru')),
            ('matatua', _('Mataatua')),
            ('tepuku', _('Te Puku o te Ika')),
            ('waipouna', _('Te Waipounamu')),
    )),
