### ISSUE TITLE
Should an update on a related field update the parent model?

### ISSUE THREAD

**Issue by kmahelona** [TeHikuMedia/corpora#55]
If a QualityControl object is created or modified for a recording, should the recording's updated field be updated as well? 

This question is relevant for getting data for ML. A developer might want to refetch all new or changed data to include in a training set. They could query the recording API for `?updated__gte=today` so that they don't have to go through each recording. But nothing in the recording model itself has changed. 

Perhaps a better strategy is to include a calculated field and provide it in the /recordings/ endpoint, or we could explicitly state that the updated field returned from the recording API is different from the model field. And we could return the most recent updated of the model and all its related QualityControl objects.

**Comment by edwardabraham** [comment]
My reckon is that the best strategy would be to keep your data nicely normalised, but then  return a handy calculated field in the API. No need for the data returned by the API to reflect the model exactly. So :+1: for calculated field approach (or a database view if that is more efficient - sometimes the Django ORM can make things a bit slow).

**Comment by kmahelona** [comment]
Closed in 3600f8682bc167bd8185c74d7d8c9dfd562f9403
