### ISSUE TITLE
Add an a hash of the audio file to the model

### ISSUE THREAD

**Issue by edwardabraham** [TeHikuMedia/corpora#56]
A good idea to add an md5 hash in to the models for the audio, and return through the API. This will help us confirm that we have the same data as Kōrero Māori, and will also help you ensure that you can associate recordings with the correct files in the long term (filenames can be a bit fragile!).

**Comment by kmahelona** [comment]
S3 returns hashes, and you can get it with a HEAD request. I remember sharing this with someone earlier, but yea this should be easy to just add in the database.

**Comment by kmahelona** [comment]
This is now implemented and live in master. It will take some time to compute for all the old recordings.
