### ISSUE TITLE
Get metadata on koreromaori.io so it is pretty when shared on social media

### ISSUE THREAD

**Issue by edwardabraham** [TeHikuMedia/corpora#60]
A bit of open graph stuff needed http://ogp.me/

**Comment by kmahelona** [comment]
Thanks Ed. This is rudimentary web stuff which is on my huge to do list in my head, so I do appreciate the “checklist.” 

It’s actually partially implemented - even made a class mixin to streamline this. The challenge is making a nice picture (or what even should the picture be!). You’ll notice the text is there for the open graph I just don’t have a logo or image. Same with koreromaori.com. Ideally I’d like to hire an awesome Māori designer to solve these issues.

**Comment by kmahelona** [comment]
Placeholder image until I can get something better.
```
  <meta name="description" content="Indigenous language tools powered by machine learning." />
  <meta name="title" content="kōreromāori.io" />

  <meta property="og:type"             content="website"/>
  <meta property="og:title"            content="kōreromāori.io"/>
  <meta property="og:url"              content="https://koreromaori.io/" />
  <meta property="og:site_name"        content="kōreromāori.io"/>
  <meta property="og:description"      content="Indigenous language tools powered by machine learning."/>
  <meta property="og:image"            content="https://koreromaori.io/static/reo_api/img/home.jpg"/>

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@tehiku" />
  <meta name="twitter:title" content="kōreromāori.io" />
  <meta name="twitter:description" content="Indigenous language tools powered by machine learning." />
  <meta name="twitter:image" content="https://koreromaori.io/static/reo_api/img/home.jpg" />
```

**Comment by edwardabraham** [comment]
Yeah. We had the same issue on our website for a whole bunch of years!  Like you say, one of those small details that just needs a bit of thought .

**Comment by edwardabraham** [comment]
beat me to it :+1:

**Comment by kmahelona** [comment]
I’m at a conference so I’ve got free time 😅
