### ISSUE TITLE
Refine the review goals

### ISSUE THREAD

**Issue by edwardabraham** [TeHikuMedia/corpora#79]
I know this is already on  the to-do list, but I am raising it as an issue because when I tried out the app this morning it is clear that the review goals need refining (mainly an issue because I wasn't sure what a thumbs up or down meant exactly, see also #75 ). There are some different questions here:

1. Does the recording consist of audible speech?
2. Does the speaker read the words that were written? 
3. Does the speech flow naturally?
4. Is the pronunciation good? 

To me, numbers 2, 3, and 4 seem to align with the whakatauki "Ko te reo kia tika, ko te reo kia rere, ko te reo kia Māori", which could be a simple way to structure it.

From  a speech recognition point of view, 1 and 2 are important (although we don't mind if the audio is poor quality with background noise, as this will often be encountered in real life, just that there is recognisable speech).

**Comment by kmahelona** [comment]
this is what we have internally for hand picked reviewers,



APPROVE
Approve a recording if and only if
The person reads exactly what is written
The recording is intelligible (see below).
Pronunciation is correct (see below)

INTELLIGIBILITY
A recording is deemed intelligible if and only if
You can confirm the person read exactly what is written
You can hear each of the sounds of every word in a manner than allows you to confidently determine correct pronunciation
Notes on Background Noises
If you can determine that a person read what is written and used correct pronunciation, then it's likely that the background noise was not sufficient enough to prevent intelligibility.

If you hear background sound that's as loud as the speaker but the recording is intelligible, give the recording a Thumbs Up. This will give the person more points for their recording. This recording can be used later.

PRONUNCIATION
This focuses on the sound system of the Māori language. The consistently correct pronunciation of vowels consonants, different-vowel combinations, vowel length and dialectal variations are fundamental to the linguistic integrity of the programme as a whole. Three important areas to avoid are – 
the over-aspiration of /p/, /t/, /k/ 
the identical pronunciation of /-ai/ & /-ae/, /-au/ & /-ou/, and /-oi/ & /-oe/ 
the incorrect use of stress in multi-syllabic words.
Notes on Incorrect Pronunciation
We're training machines to understand the sounds of te reo Māori. For this reason, we can offer partial points if number (3) isn't correct.

If a person uses the incorrect stree in multi-syllabic works but pronounced all of the consonants, vowels, dipthongs, etc. correctly, then give the recording a Thumbs Up.

UNCERTAINTY
If at anytime you are uncertain about a particular recording, then either assign a Thumbs Up if you think the recording is almost correct or assign a Thumbs Down if you think the recording isn't quite correct.

**Comment by kmahelona** [comment]
@edwardabraham 

`Does the speech flow naturally?`

I guess that can be subjective but would it mean we could lose some recordings where the sounds are correct but they maybe are a little staccato?

**Comment by kmahelona** [comment]
<img width="796" alt="screen shot 2018-09-10 at 7 01 21 pm" src="https://user-images.githubusercontent.com/5294466/45281549-41af5c00-b52c-11e8-8f28-705349c66ace.png">

**Comment by edwardabraham** [comment]
Hiya,

This review task is looking much clearer.

But how about a single list, and removing the options action.  In a single
list, you could either hit the Ka Pai button which awards all the stars and
moves on, or else click the stars that apply and then hit the Kia Kaha 'sad
face didn't quite get the five stars button'.

In that way it is a single action if the recording is good, but if it is
bad in some way the reviewer needs to give more information. Problem will
be if people just hit the Kia Kaha button without giving more info.

On the recording flow question, I agree that it is arbitrary, but some
speakers take the reading very carefully, which makes it stilted. Of
course, we could get the length of the recording for each sentence, which
would tell us how fast they had read it, which may be closely related to
fluency. Another point to bear in mind is that we should learn from
sentences with a range of fluencies, so we can recognise language spoken at
any speed. So maybe leave this one out.

**Comment by kmahelona** [comment]
- Removed stars (backend is still there but for simplicity removing from UI)
- Removed "speech flows naturally"

<img width="300" alt="screen shot 2018-09-17 at 8 55 48 pm" src="https://user-images.githubusercontent.com/5294466/45613980-1690b380-babc-11e8-9803-aa07c7d83db8.png">

I think at the end of the day, we just want the "good" stuff. Knowing "why" something was bad I think would only be useful if we wanted to train something to recognise that (e.g. pronunciation). I'd like to update the UI to allow selected reviewers (versus crowd sourced reviewers) to indicate at the phoneme or word level where pronunciation is incorrect.

Closing this for now.
