### ISSUE TITLE
https://www.koreromaori.com/whakarongo/ continuously cycling every 2 seconds

### ISSUE THREAD

**Issue by orotau** [TeHikuMedia/corpora#81]
Hi there
Using either Chrome or Firefox on Ubuntu the text to listen to keeps changing every two seconds without giving me an opportunity to interact with it.

**Comment by orotau** [comment]
![screenshot from 2018-09-17 19-25-31](https://user-images.githubusercontent.com/6657957/45610283-89dff880-baaf-11e8-9bb5-d251250bc8cb.png)

**Comment by orotau** [comment]
![screenshot from 2018-09-17 19-30-42](https://user-images.githubusercontent.com/6657957/45610498-34581b80-bab0-11e8-94a0-aa22363694de.png)
This is Chrome

**Comment by kmahelona** [comment]
Can you confirm whether your full domain is "www.koreromaori.com" or "koreromaori.com." Somehow redirects aren't working (www.koreromaori.com => koreromaori.com), and I've just discovered that if you're at www.koreromaori.com then you'll encounter this error.

**Comment by orotau** [comment]
yes that seems to work (removing the www from the url)

**Comment by kmahelona** [comment]
Cool. I've updated the back-end so www will redirect to the non-www domain.
