### ISSUE TITLE
Duplicate records in the recordings API

### ISSUE THREAD

**Issue by mathematiguy** [TeHikuMedia/corpora#93]
I think I've spotted some duplicate records in the recordings API while working on our pipelines.

Here are the ids for the duplicated records, which each appear to have exactly two records in the API:
195668, 194714, 194591, 194588, 195669, 195464, 194590, 194587, 195667, 195479, 194918, 194642, 195465, 195666, 195468, 194917, 194593, 194705, 194707, 194711

I thought maybe that scrapy was sending duplicate requests by accident, but I was able to confirm that at a minmum:
https://koreromaori.com/api/recordings/?format=json&page=2
and
https://koreromaori.com/api/recordings/?format=json&page=19538
Both contain records with the id 195669

I also made some changes to my code to (I think) remove the possibility of duplicates, but it could still be a problem on my end. In any case, I think there's enough here to merit some investigation.

For the sake of the work I'm doing, I just did deduplication myself after downloading all of the json. But it'll probably be best in the long run to double check this.

**Comment by edwardabraham** [comment]
Just bumping this  to check that it is fixed.

**Comment by mathematiguy** [comment]
Yep, this issue is solved - We got @kmahelona to sort the json entries so that new records are only appended to the end.

This was important because when the scraper steps through the records, if new ones are being added to the beginning the rest shift over one and you start getting double ups.
